### ISSUE TITLE
powernukkit

### ISSUE THREAD

**Issue by feanchy** [tim03we/InvSeeNK#1]
this plugin crashes when writing /invsee and /ec on powernukkit

**Comment by tim03we** [comment]
Error?

**Comment by feanchy** [comment]
at tim03we.invsee.commands.InvSeeCommand.execute(InvSeeCommand.java:47) ~[?:?]
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:258) ~[powernukkit.jar:?]
        at cn.nukkit.Server.dispatchCommand(Server.java:962) ~[powernukkit.jar:?]
        at cn.nukkit.Player.handleDataPacket(Player.java:3060) ~[powernukkit.jar:?]
        at cn.nukkit.network.Network.lambda$processPackets$3(Network.java:285) ~[powernukkit.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_265]
        at cn.nukkit.network.Network.processPackets(Network.java:283) ~[powernukkit.jar:?]
        at cn.nukkit.network.Network.processBatch(Network.java:269) ~[powernukkit.jar:?]
        at cn.nukkit.Player.handleDataPacket(Player.java:2303) ~[powernukkit.jar:?]
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:75) ~[powernukkit.jar:?]
        at cn.nukkit.network.Network.processInterfaces(Network.java:158) ~[powernukkit.jar:?]
        at cn.nukkit.Server.tick(Server.java:1361) ~[powernukkit.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:1144) [powernukkit.jar:?]
        at cn.nukkit.Server.start(Server.java:1104) [powernukkit.jar:?]
        at cn.nukkit.Server.<init>(Server.java:760) [powernukkit.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:120) [powernukkit.jar:?]

**Comment by tim03we** [comment]
Please send me the complete error, including what is written about it.

**Comment by tim03we** [comment]
Either the FakeInventories plugin is not on it or you have the wrong version. Please use this one instead: [https://workupload.com/file/UBtJUACEApU](https://workupload.com/file/UBtJUACEApU)

**Comment by feanchy** [comment]
thank you.
